### ISSUE TITLE
Possible wrong file descriptor value?

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/pragzip#1]
https://github.com/mxmlnkn/pragzip/blob/653b9e6bbba86c0c3e2eb743265517a105843d83/src/pragzip/ParallelGzipReader.hpp#L240
Maybe i'm wrong on this but it seems that this default -1 value for file descriptor will be passed on **write** syscall

**Comment by mxmlnkn** [comment]
Negative file descriptors (a hack for an optional-like interface) are filtered in this [writeAll](https://github.com/mxmlnkn/pragzip/blob/653b9e6bbba86c0c3e2eb743265517a105843d83/src/core/FileUtils.hpp#L276) overload.

That the file descriptor to the read call is used for a `write` is as it should be. This is the output file descriptor into which the decompressed result will be written.

Did you have any specific bug that got you looking into this particular code?

**Comment by Vadiml1024** [comment]
Ah..  I' ve missed this overload... 
I don' t have any specific bug, i'm thinking about using pragzip in one of the projects i' m working on, so i' m browsing through the code.

**Comment by mxmlnkn** [comment]
> Ah.. I' ve missed this overload... I don' t have any specific bug, i'm thinking about using pragzip in one of the projects i' m working on, so i' m browsing through the code.

Ok, note that the most important missing "feature" is any kind of memory limit control for very high compression ratios. See #2.
